### ISSUE TITLE
Lets get started page typo

### ISSUE THREAD

**Issue by manstis** [karreiro/learn-dmn-in-15-minutes#4]
The first popup "Let's get started" contains a typo.

"some possible **enhacement**" s/b "some possible **enhancement**".

![Screenshot from 2020-03-26 10-59-38](https://user-images.githubusercontent.com/497544/77639702-0f6c2080-6f51-11ea-95dc-2fdcabaa3c9c.png)

**Comment by karreiro** [comment]
Thank you very much, @manstis! :) Fixed by https://github.com/karreiro/learn-dmn-in-15-minutes/commit/59f54b1ceaedc85f60b985e9a053fe56a9f4618e
