### ISSUE TITLE
Data Types page typo

### ISSUE THREAD

**Issue by manstis** [karreiro/learn-dmn-in-15-minutes#5]
The wording of the sentence "On this example, the decision node probably as a decision logic (e.g., a decision table) that checks the input nodes..." could be improved. Possibly "On this example, the decision node, possibly a decision table, checks the input nodes..."

The page also contains a typo: 

"The DMN Specification often **refeers** to..." s/b "The DMN Specification often **refers** to..."

![Screenshot from 2020-03-26 11-05-32](https://user-images.githubusercontent.com/497544/77640339-20696180-6f52-11ea-839c-f2b4e602a366.png)

**Comment by karreiro** [comment]
Thank you, @manstis! This one was fixed by https://github.com/karreiro/learn-dmn-in-15-minutes/pull/7
