### ISSUE TITLE
The FEEL language page typo

### ISSUE THREAD

**Issue by manstis** [karreiro/learn-dmn-in-15-minutes#6]
"Here you've learned the most frequently used FEEL **structures**..." should possibly be "Here you've learned the most frequently used FEEL **functions**..." or "Here you've learned the most frequently used FEEL **expressions**..." but I felt _structures_ was wrong?

![Screenshot from 2020-03-26 11-11-59](https://user-images.githubusercontent.com/497544/77640667-b9987800-6f52-11ea-91d4-4a85c3ca6e6e.png)

**Comment by karreiro** [comment]
Thank you very much, @manstis! :) Fixed by 59f54b1
