### ISSUE TITLE
Small notes during study in 15 minutes

### ISSUE THREAD

**Issue by dupliaka** [karreiro/learn-dmn-in-15-minutes#8]
On Simple data types step if you forget to choose a type of the variable and press save - then you will see a window oops without any cross in there so you trapped in this state. See [1] 

Navigation on right panel is impossible after entering "Visual notation" and "Simple data types". If I want to go back or skip it i need to use arrows under the content(right panel as well)

The link "here" is not clickable [2] though you can go there by clicking right click -> open in separate.

[1]
![image](https://user-images.githubusercontent.com/21653197/77927540-a31e5380-72a7-11ea-84b8-a0280bb352f5.png)

[2] 
![image](https://user-images.githubusercontent.com/21653197/77927034-24c1b180-72a7-11ea-8276-a95d507d4e65.png)

**Comment by karreiro** [comment]
Resolved by https://github.com/karreiro/learn-dmn-in-15-minutes/commit/a775b63395a4f1084574c430b4489205948036a4
